### ISSUE TITLE
You stole my codes

### ISSUE THREAD

**Issue by chzdo** [JaneRapley/PasswordGeneratorHomework4#1]
for(var i = 0; i < options.length; i++){

   let garCharactersOpt = garCharacters[getRandom(garCharacters.length)];
   let passwordOptionChar = passwordCharacters[garCharactersOpt];
   result.push(passwordOptionChar[getRandom(passwordOptionChar.length)])

  }
   return result.join("");

you stole this code from me from freelancer.

This is not right and i hope your instructor sees this

**Comment by JaneRapley** [comment]
I do apologize I didn't realize. I hired a tutor to help me with this project I am so embarrassed.
